### ISSUE TITLE
Merge env_file into environment directive

### ISSUE THREAD

**Issue by pradeepto** [redhat-developer/opencompose-old#18]
Does it make sense to have a separate directive for environment file?

Either of this is a valid spec and tools should be able to handle them : 

```
environment:
  - S3_BUCKET: SOME_S3_BUCKET
  - API_KEY: XYZABCDE123
  - API_SECRET:SFZV3EYT89
  - DATABASE_URL="postgres://SOME_URL"
```

```
environment:
  - /file/to/environment/variables
```

```
environment:
  - API_KEY: XYZABCDE123
  - API_SECRET:SFZV3EYT89
  - /file/to/environment/variables
```
