### ISSUE TITLE
Differentiating between Docker Compose and Open Compose

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/opencompose-old#26]
There should be some form of meta-data in order to detect / differentiate whether or not this is an Open Compose format or Docker Compose due to the similarity of the projects.

For example, either a required parameter within meta-data or something that indicates it's a different format.

For example:

```
version: "0.1"
compose-name: "helloworld"
author:
  name: Uber Hacker
  email: developer@example.com
```

Or something ^^
